core/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from .views import LoginView, SignUpView

app_name = "accounts"  # For dynamic url

urlpatterns = [
    # This url used for login
    path("login/", LoginView.as_view(), name="login"),
    # This url used for logout
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("accounts:login")),
        name="logout",
    ),
    # This url used for signup
    path("signup/", SignUpView.as_view(), name="signup"),
    # This url includes all api v1 urls for the accounts app
    path("api/v1/", include("accounts.api.v1.urls")),
    # This url includes all api v2 urls for the accounts app
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from todo import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Todo's API",
        default_version="v1",
        description="This is an api service for todo app",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mrrahbarnia@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    # ============= This url is for accessing to admin page ============= #
    path("admin/", admin.site.urls),
    # ============= Path to include accounts app urls ============= #
    path("accounts/", include("accounts.urls")),
    # ============= This url is for creating todos ============= #
    path("", views.CreateTodoView.as_view(), name="todo-create"),
    # ============= This url is for deleting todos ============= #
    path("<int:pk>/delete/",
         views.DeleteTodoView.as_view(),
         name="todo-delete"),
    # ============= This url is for updating todos ============= #
    path("<int:pk>/edit/", views.UpdateTodoView.as_view(), name="todo-edit"),
    # ============= This url used for weather condition ============= #
    path("weather/", views.open_weather, name="weather"),
    # This url used for login/logout cause we are gonna use browsable api
    path("api-auth/", include("rest_framework.urls")),
    # ============= This url includes todo API urls ============= #
    path("api/v1/", include("todo.api.v1.urls")),
    # These are url's of swagger and redoc documentations
    path(
        "swagger/api.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui"),
    path("redoc/",
         schema_view.with_ui("redoc", cache_timeout=0),
         name="schema-redoc")
]
# Only for development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/todo/api/v1/urls.py
from rest_framework import routers
from .views import TodoModelViewSet

app_name = "todo-api"

# Defaultrouter for generating all url's which belong to todo app
router = routers.DefaultRouter()
router.register("todo", TodoModelViewSet, basename="todo")

urlpatterns = router.urls

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import Truncator

# My user model
user = get_user_model()

complete_choices = [
    ("complete", "complete"),
    ("pending", "pending")
]


# ============= This class defines the todo model attributes ============= #
class Todo(models.Model):

    user = models.ForeignKey(user, on_delete=models.CASCADE)
    task = models.CharField(max_length=1000, unique=True)
    complete = models.CharField(
        max_length=8, choices=complete_choices, default='pending'
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task[:50]

    def title_snippet(self):
        # ============= This class used for todo api serilizer ============= #
        truncated_task = Truncator(self.task).words(4)
        return truncated_task

core/todo/forms.py
from django import forms
from .models import Todo


# This class defines todo form fields and their attributes
class TodoForm(forms.ModelForm):
    title = forms.CharField(
        max_length=1000,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Please enter the tasks here"}
        ),
    )

    class Meta:
        model = Todo
        fields = ("title",)

core/todo/api/v1/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from ...models import Todo
from .serializers import TodoSerializer
from .permissions import IsOwnerOrReadOnly
from .paginations import CustomPagination


class TodoModelViewSet(viewsets.ModelViewSet):
    # CRUD with one view based on ModelViewSet
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    ]
    filterset_fields = {"user__username": ["exact", "in"]}
    search_fields = ["task", "=user__username"]
    ordering_fields = ["created_at"]
    pagination_class = CustomPagination
    # Listing the tasks which belong to existing user
    # def get_queryset(self):
    #     user = self.request.user
    #     queryset = Todo.objects.filter(user=user)
    #     return queryset

core/todo/views.py
from django.views.generic import (
    CreateView,
    DeleteView,
    UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.cache import cache_page
from django.http import HttpResponse

import requests

from .models import Todo
from .forms import TodoForm


# This class used for creating todos and listing them by "todos"
class CreateTodoView(LoginRequiredMixin, CreateView):
    model = Todo
    template_name = "todo/todo_list.html"
    form_class = TodoForm
    success_url = "/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateTodoView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todos"] = self.model.objects.filter(user=self.request.user)
        return context


# This class used for deleting todos
class DeleteTodoView(LoginRequiredMixin, DeleteView):
    model = Todo
    success_url = "/"

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


# This class used for updating todos
class UpdateTodoView(LoginRequiredMixin, UpdateView):
    model = Todo
    success_url = "/"
    form_class = TodoForm

@cache_page(60*20)
def open_weather(request):
    r = requests.get(
        "http://api.weatherapi.com/v1/forecast.json?key=3c6faa14b58a4a9ebae141433232809&q=Tehran&days=1&aqi=no&alerts=no"
        ).json()
    condition = f"The weather is {r['current']['condition']['text']} today"
    return HttpResponse(f"<h1>{condition}</h1>")

core/templates/todo/todo_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

<!--=====================Block for title of the page=====================-->
{% block title %}
Todo edit
{% endblock title %}

<!--=====================Block for navbar-content=====================-->
{% block navbar-content %}
<a class="navbar-brand flex-grow-1" style="text-align: center; color: #fff; margin-left: 25px;">
    Todo-app
</a> 
{% endblock navbar-content %}

<!--=====================Block for navbar-button login or logout=====================-->
{% block navbar-button %}
<a href="{% url 'accounts:logout' %}" class="btn btn-outline-light border-light btn-sm" id="btn-nav">Logout</a>
{% endblock navbar-button %}



<!--=====================Block for content of this page=====================-->
{% block container %}
<div class="container mt-3" style="width: 95%; font-size: 14px;">
    <form method="post" action="{% url 'todo-edit' pk=object.id %}" autocomplete="off" novalidate>
        {% csrf_token %}
        <div class="col-6">
            {{ form.title|as_crispy_field }}
        </div>
        <button class="btn btn-outline-light border-dark btn-sm">Change Task</button>
    </form>
</div>
{% endblock container %}

core/templates/todo/todo_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

<!--=====================Block for title of the page=====================-->
{% block title %}
Todo list
{% endblock title %}

<!--=====================Block for navbar-content=====================-->
{% block navbar-content %}
<a class="navbar-brand flex-grow-1" style="text-align: center; color: #fff; margin-left: 25px;">
    Todo-app
</a> 
{% endblock navbar-content %}

<!--=====================Block for navbar-button login or logout=====================-->
{% block navbar-button %}
<a href="{% url 'accounts:logout' %}" class="btn btn-outline-light border-light btn-sm" id="btn-nav">Logout</a>
{% endblock navbar-button %}



<!--=====================Block for content of this page=====================-->
{% block container %}
<div class="container mt-3" style="width: 95%; font-size: 14px;">
    <form method="post" action="{% url 'todo-create' %}" autocomplete="off" novalidate>
        {% csrf_token %}
        <div class="col-6">
            {{ form.title|as_crispy_field }}
        </div>
        <button class="btn btn-outline-light border-light btn-sm" style="width: 50%;">Add Task</button>
    </form>
</div>
<br/>
{% for i in todos %}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="btn btn-outline-light border-light btn-sm mt-2">
                <span>{{i}}</span>
            </div>
            <a href="{% url 'todo-edit' pk=i.id %}" class="btn btn-outline-light border-light btn-sm mt-2" id="btn-nav">
                Edit
            </a>
            <a href="{% url 'todo-delete' pk=i.id %}" class="btn btn-outline-light border-light btn-sm mt-2" id="btn-nav">
                Done
            </a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock container %}